/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Blake3Hasher {
  static deriveKey(context: string, keyMaterial: Uint8Array): Buffer
  constructor()
  static newKeyed(key: Buffer): Blake3Hasher
  static newDeriveKey(input: string): Blake3Hasher
  reset(): void
  update(input: string | Uint8Array | number): this
  digest(): Buffer
}

export declare function blake3(input: string | Uint8Array): Buffer
